main:
  - name: About
    url: '#about'
    weight: 10
  - name: Publications
    url: '#publications'
    weight: 20
  - name: Conferences
    url: '#conference'
    weight: 30
  - name: Teaching
    url: '#teaching'
    weight: 40
  - name: Awards
    url: '#accomplishment'
    weight: 50
  - name: Experience
    url: '#experience'
    weight: 20
